# Generated by Django 4.2.20 on 2025-04-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0001_alter_chat_ai_model'),
        ('bot_admin', 'update_default_model'),
    ]

    operations = [
    ]
