# Generated by Django 4.2.20 on 2025-04-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0002_plan_referral_userplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_system', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payments',
                'ordering': ['-payment_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма'), ('requests', 'Бонусные запросы')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_requests', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_usages', models.IntegerField(default=0)),
                ('usages_count', models.IntegerField(default=0)),
                ('allowed_plans', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'promo_codes',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referral_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bonus_requests_added', models.IntegerField(default=0)),
                ('conversion_status', models.CharField(default='registered', max_length=50)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'История реферралов',
                'verbose_name_plural': 'История реферралов',
                'db_table': 'referral_history',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=50)),
                ('ai_model', models.CharField(max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('was_successful', models.BooleanField(default=True)),
                ('request_text', models.TextField(blank=True, null=True)),
                ('response_length', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Использование запроса',
                'verbose_name_plural': 'Использование запросов',
                'db_table': 'request_usage',
                'ordering': ['-request_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_referrals', models.IntegerField(default=0)),
                ('favorite_model', models.CharField(blank=True, max_length=100, null=True)),
                ('account_level', models.CharField(default='standard', max_length=50)),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистика пользователей',
                'db_table': 'user_statistics',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'managed': False, 'ordering': ['priority', 'price'], 'verbose_name': 'Тарифный план', 'verbose_name_plural': 'Тарифные планы'},
        ),
    ]
