# Generated by Django 4.2.20 on 2025-04-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0002_merge_0001_alter_chat_ai_model_update_default_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='ai_model',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('claude-3-5', 'Claude 3.5'), ('claude-3-7', 'Claude 3.7'), ('gemini-2-flash', 'Gemini 2.0 Flash'), ('gpt-4', 'GPT-4'), ('gpt3-mini', 'GPT-3 Mini'), ('dall-e', 'DALL-E'), ('midjourney', 'Midjourney')], default='gpt-4o-mini', max_length=50),
        ),
    ]
