# Generated by Django 4.2.20 on 2025-04-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0003_alter_chat_ai_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_uses', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Реферальный код',
                'verbose_name_plural': 'Реферальные коды',
                'db_table': 'referral_codes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'db_table': 'requests',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='referralhistory',
            name='referred_user',
        ),
        migrations.AddField(
            model_name='referralhistory',
            name='referred',
            field=models.ForeignKey(blank=True, db_column='referred_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_source', to='bot_admin.botuser'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='requests_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='bot_admin.botuser'),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to='bot_admin.botuser'),
        ),
        migrations.AlterField(
            model_name='referralhistory',
            name='referral_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='bot_admin.referralcode'),
        ),
    ]
